export const perfumeData = [
  {
    marca: "Hollister",
    nombre: "Festival Vibes",
    precio: 700,
    disponible: true,
    imagen: "/images/perfume01.png",
  },
  {
    marca: "Tommy Hilfiger",
    nombre: "tommy girl",
    precio: 800,
    disponible: true,
    imagen: "/images/perfume01.png",
  },
  {
    marca: "DOLCE & GABBANA",
    nombre: "Light Blue - Dama",
    precio: 2100,
    disponible: true,
    imagen: "/images/perfume01.png",
  },
  {
    marca: "Lanvin - Paris",
    nombre: "Lanvin",
    precio: 1000,
    disponible: true,
    imagen: "/images/perfume01.png",
  },
  {
    marca: "Perry Ellis",
    nombre: "360° Red - CABALLERO",
    precio: 800,
    disponible: true,
    imagen: "/images/perfume01.png",
  },
  {
    marca: "Lanvin - Paris",
    nombre: "A girl in Capri",
    precio: 1200,
    disponible: true,
    imagen: "/images/perfume01.png",
  },
  {
    marca: "Dolce & Gabbana",
    nombre: "Devotion",
    precio: 2000,
    disponible: true,
    imagen: "/images/perfume01.png",
  },
  {
    marca: "Dolce & Gabbana",
    nombre: "Light Blue - Caballero",
    precio: 1500,
    disponible: true,
    imagen: "/images/perfume01.png",
  },
  {
    marca: "Carlo Corinto",
    nombre: "One Night - Dama",
    precio: 1200,
    disponible: true,
    imagen: "/images/perfume01.png",
  },
  {
    marca: "Carlo Corinto",
    nombre: "One Night - Caballero",
    precio: 1200,
    disponible: true,
    imagen: "/images/perfume01.png",
  },
  {
    marca: "Diesel",
    nombre: "Living for successful",
    precio: 1300,
    disponible: true,
    imagen: "/images/perfume01.png",
  },
  {
    marca: "Billie Eilish",
    nombre: "Eilish No. 2",
    precio: 1400,
    disponible: true,
    imagen: "/images/perfume01.png",
  },
  {
    marca: "Versace",
    nombre: "Dylan Purple - Dama",
    precio: 1800,
    disponible: true,
    imagen: "/images/perfume01.png",
  },
  {
    marca: "Chrome",
    nombre: "Azzaro",
    precio: 1400,
    disponible: true,
    imagen: "/images/perfume01.png",
  },
  {
    marca: "Coach Dreams",
    nombre: "Sunset",
    precio: 1000,
    disponible: true,
    imagen: "/images/perfume01.png",
  },
  {
    marca: "MontBlanc Explorer",
    nombre: "MontBlanc Explorer",
    precio: 1000,
    disponible: true,
    imagen: "/images/perfume01.png",
  },
  {
    marca: "Kate Spade",
    nombre: "Kate Spade New York",
    precio: 1000,
    disponible: true,
    imagen: "/images/perfume01.png",
  },
];
