export const perfumeData = [
  {
    marca: "Hollister",
    nombre: "Festival Vibes",
    precio: 700,
    disponible: true,
    imagen: "/images/hollister.png",
  },
  {
    marca: "Tommy Hilfiger",
    nombre: "tommy girl",
    precio: 800,
    disponible: false,
    imagen: "/images/tommy.png",
  },
  {
    marca: "DOLCE & GABBANA",
    nombre: "Light Blue - Dama",
    precio: 2100,
    disponible: false,
    imagen: "/images/dolce-light-woman.png",
  },
  {
    marca: "Lanvin - Paris",
    nombre: "Lanvin",
    precio: 1000,
    disponible: true,
    imagen: "/images/lanvin.png",
  },
  {
    marca: "Perry Ellis",
    nombre: "360° Red - CABALLERO",
    precio: 800,
    disponible: true,
    imagen: "/images/360.png",
  },
  {
    marca: "Lanvin - Paris",
    nombre: "A girl in Capri",
    precio: 1200,
    disponible: true,
    imagen: "/images/lanvin-girl.png",
  },
  {
    marca: "Dolce & Gabbana",
    nombre: "Devotion",
    precio: 2000,
    disponible: true,
    imagen: "/images/dolce-devotion.png",
  },
  {
    marca: "Dolce & Gabbana",
    nombre: "Light Blue - Caballero",
    precio: 1500,
    disponible: true,
    imagen: "/images/dolce-light-man.png",
  },
  {
    marca: "Carlo Corinto",
    nombre: "One Night - Dama",
    precio: 1200,
    disponible: true,
    imagen: "/images/one-woman.png",
  },
  {
    marca: "Carlo Corinto",
    nombre: "One Night - Caballero",
    precio: 1200,
    disponible: true,
    imagen: "/images/carlo-man.png",
  },
  {
    marca: "Diesel",
    nombre: "Living for successful",
    precio: 1300,
    disponible: true,
    imagen: "/images/diesel.png",
  },
  {
    marca: "Billie Eilish",
    nombre: "Eilish No. 2",
    precio: 1400,
    disponible: true,
    imagen: "/images/billie.png",
  },
  {
    marca: "Versace",
    nombre: "Dylan Purple - Dama",
    precio: 1800,
    disponible: true,
    imagen: "/images/versace.png",
  },
  {
    marca: "Chrome",
    nombre: "Azzaro",
    precio: 1400,
    disponible: true,
    imagen: "/images/crome.png",
  },
  {
    marca: "Coach Dreams",
    nombre: "Sunset",
    precio: 1000,
    disponible: true,
    imagen: "/images/coach-solo.png",
  },
  {
    marca: "MontBlanc Explorer",
    nombre: "MontBlanc Explorer",
    precio: 1000,
    disponible: true,
    imagen: "/images/montblanc.png",
  },
  {
    marca: "Kate Spade",
    nombre: "Kate Spade New York",
    precio: 1000,
    disponible: true,
    imagen: "/images/kate.png",
  },
  {
    marca: "COACH DREAMS",
    nombre: "Sunset - Estuche",
    precio: 1500,
    disponible: true,
    imagen: "/images/coach-estuche.png",
  },
];
